name: bookfair
region: nyc

services:
  - name: web
    github:
      repo: thingvallatech/bookfair
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: node build
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
